#Practical-01(Numpy)
Khushi Ramolia


In [3]:
#creating vector
import  numpy as np
# Create a row vector
row=np.array([1,2,3,4])
# Create a column vector
column=np.array([[1],[2],[3]])
print(row)
print(column)

[1 2 3 4]
[[1]
 [2]
 [3]]


In [2]:
# Create a 2D matrix
matrix=np.array([[1,2],[3,4],[5,7]])
print(matrix)

[[1 2]
 [3 4]
 [5 7]]


In [4]:
#Creating sparse matrix
from scipy import sparse
matrix=np.array([[0,0],[0,1],[4,0]])
# Convert dense matrix to Compressed Sparse Row (CSR) format
matrix_sparse=sparse.csr_matrix(matrix)
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	4


In [5]:
#Select one or more elements of a vector
vector=np.array([1,2,3,4,5,6])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vector[3])# Select single element
print(matrix[2,1])# Select element from matrix
print(matrix[:2,:])# Slice rows and columns

4
8
[[1 2 3]
 [4 5 6]]


In [7]:
#describing a matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.shape)# Shape of matrix (rows, columns)
print(matrix.size)# Total number of elements
print(matrix.ndim)# Number of dimensions

(3, 3)
9
2


In [9]:
#applying operations
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
add_1000=lambda i:i+1000
# Vectorize function to apply element-wise
vectorized_add_1000= np.vectorize(add_1000)
print(vectorized_add_1000(matrix))
# Direct arithmetic operation
print(matrix+2000)

[[1001 1002 1003]
 [1004 1005 1006]
 [1007 1008 1009]]
[[2001 2002 2003]
 [2004 2005 2006]
 [2007 2008 2009]]


In [10]:
#finding maximum and minimum
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.max(matrix))# Max value
print(np.min(matrix))# Min value
print(np.min(matrix,axis=0)) # Min along columns
print(np.max(matrix,axis=0))# Max along columns
print(np.max(matrix,axis=1))# Max along rows
print(np.min(matrix,axis=1)) # Min along rows

9
1
[1 2 3]
[7 8 9]
[3 6 9]
[1 4 7]


In [11]:
#Calculating the Average,Variance, and Standard Deviation
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.mean(matrix))# Mean of all elements
print(np.var(matrix)) # Variance
print(np.std(matrix))# Standard Deviation
print(np.mean(matrix,axis=0))# Column-wise mean

5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]


In [12]:
#reshaping arrays
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix.reshape(6,2))# Reshape to 6x2
print(matrix.size)# Number of elements
print(matrix.reshape(1,-1))# Flatten to 1 row
matrix.reshape(12) # Flatten to 1D

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
12
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
#transposing a vector matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix.T)# Transpose matrix
print(np.array([1,2,3,4,5,6]).T)# Transpose 1D array (unchanged)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[1 2 3 4 5 6]


In [14]:
#flattening a matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix.flatten()# Flatten matrix to 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
#finding a rank of matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.linalg.matrix_rank(matrix))# Rank

2


In [17]:
#calculating determinant
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.det(matrix))# Determinant

0.0


In [19]:
#getting diagonal of matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.diagonal())# Main diagonal
print(matrix.diagonal(offset=1))# Upper diagonal
print(matrix.diagonal(offset=-1)) #Lower diagonal

[1 5 9]
[2 6]
[4 8]


In [20]:
#calculating trace of matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.trace())# Trace
print(sum(matrix.diagonal()))# Equivalent

15
15


In [22]:
#finding Eigenvalues and Eigenvectors
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenvalues,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [23]:
#calculate dot products
vector_a=np.array([1,2,3])
vector_b=np.array([4,5,6])
print(np.dot(vector_a,vector_b))# Dot product

32


In [24]:
#adding and subtracting matrices
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[5,2,3],[2,5,6],[6,1,9]])
print(np.add(matrix1,matrix2))# Addition
print(np.subtract(matrix1,matrix2))# Subtraction

[[ 6  4  6]
 [ 6 10 12]
 [13  9 18]]
[[-4  0  0]
 [ 2  0  0]
 [ 1  7  0]]


In [25]:
#multiplying matrices
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[5,2,3],[2,5,6],[6,1,9]])
np.dot(matrix1,matrix2)# Matrix multiplication

array([[ 27,  15,  42],
       [ 66,  39,  96],
       [105,  63, 150]])

In [26]:
#inverting matrices
matrix=np.array([[1,2],[3,4]])
np.linalg.inv(matrix) # Inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
#generating random values
np.random.seed(0)# Fix seed
np.random.random(3)
# Random floats [0,1)


array([0.5488135 , 0.71518937, 0.60276338])

In [30]:
np.random.randint(0,10,4)# Random integers

array([3, 7, 9, 3])

In [31]:
np.random.normal(0.0,1.0,3)# Normal distribution

array([-0.84272405,  1.96992445,  1.26611853])

In [32]:
np.random.logistic(0.0,1.0,4)# Logistic distribution

array([ 0.1157086 ,  0.27387744,  2.52093742, -2.57088231])

In [33]:
np.random.uniform(1.0,3.0,4)# Uniform distribution

array([1.1742586 , 1.04043679, 2.66523969, 2.5563135 ])