#PRACTICAL 2
KHUSHI RAMOLIA
MACHINE LEARNING LAB


In [1]:
#import numpy package and print numpy version and configurtion
import numpy as np
# Print numpy version

print(np.__version__)
# Show numpy configuration (libraries, optimizations, etc.)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [3]:
#create a null vector of size 10
a= np.zeros(10)# Create an array of 10 zeros
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#how to find memory size of any array
a=np.zeros((12,11)) # 12x11 matrix of zeros
print("%d bytes " % (a.size * a.itemsize)) # size * size of each element in bytes

1056 bytes 


In [5]:
#How to get the documenttion of the numpy add function from the command line
import numpy as np
np.info(np.add) # Prints docstring/help of np.add function

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [8]:
#Create a vector with values ranging from 10 to 49
a=np.arange(10,50)# Array of integers from 10 to 49
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#reverse vector
a=np.arange(40) # 0 to 39
a=a[::-1]# Reverse using slicing
print(a)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [10]:
#Create a 3*3 matrix with values ranging from 0 to 8 **bold text
a= np.arange(9).reshape(3,3) # Reshape into 3x3
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#Find indices of non-zero elements from 1,2,0,0,4,0
a=np.nonzero([1,2,0,0,4,0]) # Returns tuple of indices where values ≠ 0
print(a)

(array([0, 1, 4]),)


In [13]:
#Reshape into 3x3 matrix
a=np.arange(9).reshape(3,3); print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
# Random 3×3×3 matrix
a=np.random.random((3,3,3)); print(a)

[[[0.99675659 0.69541805 0.99038384]
  [0.1300193  0.28887185 0.93764961]
  [0.48214904 0.57255213 0.6575797 ]]

 [[0.02465408 0.94596311 0.59416395]
  [0.68498551 0.83957402 0.10339369]
  [0.57061511 0.78073131 0.65601066]]

 [[0.4145383  0.69894731 0.00575979]
  [0.36909067 0.00838476 0.61494299]
  [0.54790528 0.44559597 0.46369901]]]


In [15]:
# Random 10×10 matrix min & max
a=np.random.random((10,10)); print(a.min(), a.max())

0.019693898842963242 0.9964338443480855


In [16]:
#create a random vector of size 30 and find the mean value
a=np.random.random(30)
a=a.mean() # Compute mean
print(a)

0.502536881324102


In [17]:
#create a 2d array with 1 on the border and 0 inside
a=np.ones((11,11))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
#adding boarder to array
a=np.ones((6,6))
a=np.pad(a,pad_width=2,mode='constant',constant_values=0)# Pad with zeros
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
#what is the result of the following expression
print(0*np.nan) # NaN propagation
print(np.nan==np.nan)# False (NaN != NaN)
print(np.inf> np.nan)# False
print(np.inf)# Infinity
print(np.nan-np.nan)# NaN
print(np.nan in set([np.nan]))# True (Python set treats NaN as equal)
print(0.3==3*0.1)# Floating-point precision issue
print(np.nan)
print(0.3)
print(3*0.1)
print(np.inf>10000000)

nan
False
False
inf
nan
True
False
nan
0.3
0.30000000000000004
True


In [20]:
#Create a 5,5 matrix with values 1,2,3,4 just below the diagonal
a= np.diag(1+np.arange(4),k=1)# Diagonal shifted by 1
print(a)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [21]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
a = np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))# Convert flat index → 3D index

(np.int64(1), np.int64(5), np.int64(3))


In [23]:
#Create a checkerboard 8x8 matrix using the tile function
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
#Normalize a 5,5 random matrix
a=np.random.random((5,5))
print(a)
print(np.mean(a))# Mean
print(np.std(a))# Standard deviation
a=(a - np.mean(a)) / (np.std(a))# Normalization
print(a)

[[0.82735072 0.49734245 0.01455381 0.57217026 0.29958979]
 [0.82455912 0.08886553 0.59126408 0.7443599  0.33692581]
 [0.46231273 0.54206323 0.76248753 0.82862    0.05309377]
 [0.40886338 0.6337694  0.17995616 0.1963835  0.81568212]
 [0.26448409 0.29802683 0.14373364 0.85139052 0.26596713]]
0.46015262067028856
0.26975622930501275
[[ 1.36122195  0.13786457 -1.65185734  0.41525504 -0.59521454]
 [ 1.35087335 -1.37638003  0.4860368   1.05357077 -0.45680802]
 [ 0.00800764  0.30364679  1.12077082  1.36592723 -1.50898776]
 [-0.19013182  0.6436062  -1.03870245 -0.9778055   1.31796585]
 [-0.72535315 -0.60100851 -1.17298118  1.45033872 -0.71985544]]


In [25]:
#Given a 1d array,negate all elements which are between 3 and 8,in place
a=np.arange(11)
print(a)
a[(3<a) & (a<=8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [26]:
#Consider an integer vector a, which of these expressions are legal?
a=4
a**a
print(a**a) # Exponentiation
print(2<<a>>2)# Bit shifting
print(a<- a)# Comparison
print(1j*a)# Complex multiplication
print(a/1/1)# Division
print(a<a>a)# Chained comparison (always False)

256
8
False
4j
4.0
False


In [27]:
#How to find common values between two arrays
a=np.random.randint(0,10,10)
print(a)
a2=np.random.randint(0,10,10)
print(a2)
print(np.intersect1d(a,a2))# Intersection

[8 7 8 6 5 7 8 4 6 2]
[2 9 3 8 7 3 8 9 1 5]
[2 5 7 8]


In [28]:
#get dates
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [29]:
#How to get all the dates corresponding to the month of July 2016?
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]'); print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [30]:
# Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10); print(Z); print(Z.astype(int)); print(np.floor(Z)); print(np.ceil(Z)-1); print(np.trunc(Z))

[6.95475814 5.50887611 3.41534836 9.47085233 4.4746592  2.49574113
 9.30474251 4.93986093 5.07520117 0.89986066]
[6 5 3 9 4 2 9 4 5 0]
[6. 5. 3. 9. 4. 2. 9. 4. 5. 0.]
[6. 5. 3. 9. 4. 2. 9. 4. 5. 0.]
[6. 5. 3. 9. 4. 2. 9. 4. 5. 0.]


In [31]:
#Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5)); Z += np.arange(5); print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [32]:
#Create a random vector of size 10 and sort it
Z = np.random.random(10); Z.sort(); print(Z)

[0.17779332 0.20335308 0.24822375 0.49770604 0.52418028 0.57308453
 0.6246924  0.71617301 0.8543661  0.97954155]


In [33]:
#Consider two random array A and B, check if they are equal
A = np.random.randint(0,2,5); B = np.random.randint(0,2,5); print(np.allclose(A,B)); print(np.array_equal(A,B))

False
False


In [34]:
#Make an array immutable (read-only)
Z = np.zeros(10); Z.flags.writeable = False; print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
#Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]: print(np.iinfo(dtype).min, np.iinfo(dtype).max);
for dtype in [np.float32, np.float64]: print(np.finfo(dtype).min, np.finfo(dtype).max, np.finfo(dtype).eps)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38 1.1920929e-07
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


In [36]:
#How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100); v = np.random.uniform(0,100); index = (np.abs(Z-v)).argmin(); print(Z[index])

12


In [37]:
#Consider a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((3,2)); X,Y = np.atleast_2d(Z[:,0]), Z[:,1]; D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2); print(D)

[[0.         0.18576105 0.13509552]
 [0.18576105 0.         0.05066553]
 [0.13509552 0.05066553 0.        ]]


In [38]:
#How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.float32); Z = Z.astype(np.int32, copy=False); print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
#How to read the following file?
from io import StringIO; s = StringIO("1,2,3,4,5\n6,7,8,9,10\n"); Z = np.genfromtxt(s, delimiter=",", dtype=np.int); print(Z)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [40]:
#Subtract the mean of each row of a matrix
X = np.random.rand(5,10); Y = X - X.mean(axis=1, keepdims=True); print(Y)

[[ 0.17243991  0.17210175 -0.19872974  0.06409566  0.21230259 -0.08177379
  -0.01829371 -0.32174433 -0.26765877  0.26726043]
 [ 0.02294451  0.1380046   0.22202421  0.29359977 -0.09515488  0.09122055
  -0.42855539 -0.57595672  0.36220568 -0.03033232]
 [-0.40216135 -0.08589567  0.1349469  -0.22398428  0.08611257  0.51431428
  -0.03378291 -0.2687036   0.06472179  0.21443227]
 [-0.50789656  0.36272985 -0.41993394  0.31789751 -0.07452832  0.24176934
   0.21700948 -0.4610013   0.12718947  0.19676446]
 [-0.17518185 -0.12638397  0.08660397 -0.26359894 -0.21979457 -0.13998093
   0.29222769  0.10339129  0.09801444  0.34470287]]


In [41]:
#How to sort an array by the nth column?
Z = np.random.randint(0,10,(3,3)); print(Z[Z[:,1].argsort()])

[[6 0 1]
 [5 5 9]
 [1 9 4]]


In [42]:
#How to tell if a given 2D array has null columns?
Z = np.random.randint(0,3,(3,10)); print((~Z.any(axis=0)).any())

False


In [43]:
#Find the nearest value from a given value in an array
Z = np.random.uniform(0,1,10); z = 0.5; m = Z.flat[np.abs(Z-z).argmin()]; print(m)

0.4312530192382701


In [44]:
#How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
x = [1,2,3,4,5,6]; I = [1,3,9,3,4,1]; F = np.bincount(I,x); print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [45]:
#How to get the diagonal of a dot product?
A = np.random.uniform(0,1,(5,5)); B = np.random.uniform(0,1,(5,5)); print(np.sum(A*B.T, axis=1))

[0.9911318  2.09971434 1.06226568 0.91968157 1.01729009]


In [46]:
#Build a new vector with 3 consecutive zeros interleaved between each value
Z = np.array([1,2,3,4,5]); nz = 3; Z0 = np.zeros(len(Z) + (len(Z)-1)*nz); Z0[::nz+1] = Z; print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [47]:
#How to swap two rows of an array?
A = np.arange(25).reshape(5,5); A[[0,1]] = A[[1,0]]; print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
#How to compute averages using a sliding window over an array?
def moving_average(a,n=3):
  ret=np.cumsum(a,dtype=float)
  ret[n:]= ret[n:]-ret[:-n]
  return ret[n-1:]/n
a=np.arange(20)
print(moving_average(a,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [53]:
#Distance from a point to each line
def distance(P0,P1,p): T=P1-P0; L=(T**2).sum(axis=1); U=((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1])/L; U=U.reshape(len(U),1); D=P0+U*T-p; return np.sqrt((D**2).sum(axis=1))


NameError: name 'p' is not defined

In [55]:
#How to find the most frequent value in an array?
Z = np.random.randint(0,10,50); print(np.bincount(Z).argmax())

1


In [56]:
#Extract all the contiguous 3x3 blocks from a random 10x10 matrix
Z = np.random.randint(0,5,(10,10)); n=3; i=1+(Z.shape[0]-3); j=1+(Z.shape[1]-3); C=np.lib.stride_tricks.as_strided(Z, shape=(i,j,n,n), strides=Z.strides+Z.strides); print(C)

[[[[3 3 1]
   [1 3 4]
   [3 3 1]]

  [[3 1 4]
   [3 4 1]
   [3 1 2]]

  [[1 4 2]
   [4 1 1]
   [1 2 1]]

  [[4 2 2]
   [1 1 4]
   [2 1 2]]

  [[2 2 3]
   [1 4 2]
   [1 2 1]]

  [[2 3 1]
   [4 2 2]
   [2 1 1]]

  [[3 1 2]
   [2 2 3]
   [1 1 4]]

  [[1 2 2]
   [2 3 3]
   [1 4 2]]]


 [[[1 3 4]
   [3 3 1]
   [3 3 1]]

  [[3 4 1]
   [3 1 2]
   [3 1 1]]

  [[4 1 1]
   [1 2 1]
   [1 1 2]]

  [[1 1 4]
   [2 1 2]
   [1 2 1]]

  [[1 4 2]
   [1 2 1]
   [2 1 2]]

  [[4 2 2]
   [2 1 1]
   [1 2 4]]

  [[2 2 3]
   [1 1 4]
   [2 4 1]]

  [[2 3 3]
   [1 4 2]
   [4 1 2]]]


 [[[3 3 1]
   [3 3 1]
   [0 2 1]]

  [[3 1 2]
   [3 1 1]
   [2 1 1]]

  [[1 2 1]
   [1 1 2]
   [1 1 0]]

  [[2 1 2]
   [1 2 1]
   [1 0 2]]

  [[1 2 1]
   [2 1 2]
   [0 2 4]]

  [[2 1 1]
   [1 2 4]
   [2 4 4]]

  [[1 1 4]
   [2 4 1]
   [4 4 0]]

  [[1 4 2]
   [4 1 2]
   [4 0 3]]]


 [[[3 3 1]
   [0 2 1]
   [0 0 2]]

  [[3 1 1]
   [2 1 1]
   [0 2 2]]

  [[1 1 2]
   [1 1 0]
   [2 2 1]]

  [[1 2 1]
   [1 0 2]
   [2 1 0]]

  [[2 1 2]
   

In [57]:
#Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
Z = np.ones((16,16)); k=4; S=np.add.reduceat(np.add.reduceat(Z, np.arange(0,Z.shape[0],k),axis=0), np.arange(0,Z.shape[1],k),axis=1); print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [58]:
#How to get the n largest values of an array
Z = np.arange(10000); np.random.shuffle(Z); n=5; print(Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


In [59]:
#Compute bootstrapped 95% confidence intervals
X = np.random.rand(100); N=1000; idx=np.random.randint(0,X.size,(N,X.size)); means=X[idx].mean(axis=1); confint=np.percentile(means,[2.5,97.5]); print(confint)

[0.45879154 0.56578058]
